# Generated by Django 2.1.7 on 2019-05-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productotienda',
            name='imagen',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
