# Generated by Django 2.1.7 on 2019-05-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ubicaciones', '0002_auto_20190502_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productotienda',
            name='Precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
